language: generic 
sudo: required
services:
  - docker 
before_install:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker build -t c4fu/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true c4fu/react-test npm run test -- --coverage
after_success:
  - docker build -t c4fu/multi-client ./client
  - docker build -t c4fu/multi-nginx ./nginx
  - docker build -t c4fu/multi-server ./server
  - docker build -t c4fu/multi-worker ./worker
  - docker push c4fu/multi-client
  - docker push c4fu/multi-nginx 
  - docker push c4fu/multi-server
  - docker push c4fu/multi-worker
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-164691322514"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY